--Please View README Before Continuing
--Create a table that chronologically follows the csv file with correct data types
CREATE TABLE qb_data
(
	player_id VARCHAR(50),                 
	player_name VARCHAR(50),
	position VARCHAR(50),
	season INT,
	season_type VARCHAR(50),
	team VARCHAR(50),
	shotgun INT,
	no_huddle INT,
	qb_dropback INT,
	qb_scramble INT,
	pass_attempts INT,
	complete_pass INT,
	incomplete_pass INT,
	passing_yards INT,
	yards_after_catch INT,
	rush_attempts INT,
	rushing_yards INT,
	first_down_pass INT,
	first_down_rush INT,
	third_down_converted INT,
	third_down_failed INT,
	fourth_down_converted INT,
	fourth_down_failed INT,
	rush_touchdown INT,
	pass_touchdown INT,
	interception INT,
	fumble INT,
	fumble_lost INT,
	passing_air_yards INT,
	pass_attempts_redzone INT,
	complete_pass_redzone INT,
	pass_touchdown_redzone INT,
	pass_attempts_gtg INT,
	complete_pass_gtg INT,
	pass_touchdown_gtg INT,
	rush_attempts_gtg INT,
	rush_touchdown_gtg INT,
	offense_snaps INT,
	team_offense_snaps INT,
	total_tds INT,
	touches INT,
	total_yards INT,
	offense_pct FLOAT,
	games_played_season INT,
	completion_pct FLOAT,
	td_to_int_ratio FLOAT,
	red_zone_comp_pct FLOAT,
	total_turnovers INT,
	shotgun_pct FLOAT,
	dropback_pct FLOAT,
	yards_per_att FLOAT,
	td_per_att FLOAT,
	air_yds_att FLOAT,
	yds_per_rush FLOAT,
	passer_rating FLOAT
);

--Imported my CSV FILE to fill the table (cleaned_qb_data.csv)
--Make sure to check header box when importing

SELECT * FROM qb_data;