--Please View README Before Continuing
--Create a table that chronologically follows the csv file with correct data types
CREATE TABLE qb_data
(
	player_id VARCHAR(50),                 
	player_name VARCHAR(50),
	player_display_name VARCHAR(100),
	position VARCHAR(50),
	position_group VARCHAR(50),
	headshot_url TEXT,
	season INT,
	season_type VARCHAR(50),
	recent_team VARCHAR(50),
	games INT,
	completions INT,
	attempts INT,
	passing_yards INT,
	passing_tds INT,
	passing_interceptions INT,
	sacks_suffered INT,
	sack_yards_lost INT,
	sack_fumbles INT,
	sack_fumbles_lost INT,
	passing_air_yards INT,
	passing_yards_after_catch INT,
	passing_first_downs INT,
	passing_epa FLOAT,
	passing_cpoe FLOAT,
	passing_2pt_conversions INT,
	pacr FLOAT,
	passing_10 INT,
	passing_16 INT,
	passing_20 INT,
	passing_40 INT,
	carries INT,
	rushing_yards INT,
	rushing_tds INT,
	rushing_fumbles INT,
	rushing_fumbles_lost INT,
	rushing_first_downs INT,
	rushing_epa FLOAT,
	rushing_2pt_conversions INT,
	rushing_10 INT,
	rushing_12 INT,
	rushing_20 INT,
	rushing_40 INT,
	fumbles_total INT,
	fumbles_lost_total INT,
	fantasy_points FLOAT,
	fantasy_points_ppr FLOAT,
	completion_pct FLOAT,
	td_to_int_ratio FLOAT,
	total_turnovers INT,
	yards_per_att FLOAT,
	td_per_att FLOAT,
	air_yds_att FLOAT,
	yds_per_rush FLOAT,
	total_yards INT,
	total_tds INT,
	total_epa FLOAT,
	total_dropbacks INT,
	epa_per_dropback FLOAT,
	passer_rating FLOAT
);

--Imported my CSV FILE to fill the table (cleaned_qb_data.csv)

--Can use to test
SELECT * FROM qb_data;